# See for configurations: https://golangci-lint.run/usage/configuration/
version: 2

# See: https://golangci-lint.run/usage/formatters/
formatters:
  default: none
  enable:
    - gci # https://github.com/daixiang0/gci
    - gofmt # https://pkg.go.dev/cmd/gofmt
    - gofumpt # https://github.com/mvdan/gofumpt
    - goimports # https://pkg.go.dev/golang.org/x/tools/cmd/goimports

  settings:
    gci:
      sections:
        - standard
        - default
        - localmodule
    gofmt:
      simplify: true # Simplify code: gofmt with `-s` option.

    gofumpt:
      # Module path which contains the source code being formatted.
      # Default: ""
      module-path: github.com/mop-tracker/mop # Should match with module in go.mod
      # Choose whether to use the extra rules.
      # Default: false
      extra-rules: true
